name: Run main.py

on:
  schedule:
    - cron: '0 */6 * * *'  # Run every 6 hours, adjust as needed
  push:
    branches:
      - main

jobs:
  run-main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@ce73f987849b4e0a4c7a06d162c988c7d1e6f773  # Use the commit SHA
        with:
          python-version: '3.x'  # Use the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Add this line if you have any Python dependencies

      - name: Run main.py
        run: python main.py
